---
- hosts: 127.0.0.1
  connection: local
  gather_facts: false
  vars:
    app_name: test2-sc

    aws_region: eu-central-1
    aws_access_key: "{{ lookup('pipe','../../password-store/go pass show infra/aws_access_key')|quote }}"
    aws_secret_key: "{{ lookup('pipe','../../password-store/go pass show infra/aws_secret_key')|quote }}"

    db_name: sc
    db_user: sc
    db_password: "{{ lookup('pipe','../../password-store/go pass show sc_test2/rds/db_password') }}"

    frontend_cidr: 10.0.17.0/24
    env: test2

  roles:
    - frontend-host

- hosts: frontend-host
  become: yes
  vars:
    motionwerk_rsa_public: "{{ lookup('pipe','../../password-store/go pass show infra/aws_ssh_key_pub')}}"
  roles:
    - webapp
