fastlane_version "2.38.1"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    scan(
      workspace: "ShareCharge.xcworkspace",
      devices: "iPhone 6s"
      )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    # match
    gym # Build your app - more options available
    pilot
    # sh "your_script.sh"
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    # slack(message: "Successfully deployed new App Update.")
  end

  error do |lane, exception|
    # slack(message: exception.message, success: false)
  end
end

platform :android do
  # desc "Sign an APK"
  # lane :sign_apk_lane do |options|
  #     sign_apk(
  #       alias: "share_and_charge",
  #       storepass: options[:storepass],
  #       keystore_path: "fastlane/release-cred/share-and-charge.keystore",
  #       tsa: "http://timestamp.comodoca.com/rfc316",
  #       signed_apk_path: options[:signed_apk_path],
  #       keypass: options[:keypass]
  #     )
  # end
  #
  # desc "Compile new build for Android"
  # lane :release do |options|
  #   app_android__key = 'share_and_charge'
  #   sign_apk(
  #     apk_path: "./platforms/android/build/outputs/apk/android-release-unsigned.apk",
  #     signed_apk_path: "./platforms/android/build/outputs/apk/ShareAndCharge.apk",
  #     keystore_path: "./fastlane/release-cred/share-and-charge.keystore",
  #     alias: app_android__key
  #   )
  #   zipalign(apk_path: "#{lane_context[SharedValues::SIGNED_APK_PATH]}")
  # end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "deploy to google play alpha channel"
  lane :alpha do |options|
    gradle(task: "clean")
    gradle(task: "assemble")
    sign_apk(
        alias: "share_and_charge",
        storepass: options[:storepass],
        keystore_path: "./fastlane/release-cred/share-and-charge.keystore",
        tsa: "http://timestamp.comodoca.com/rfc316",
        signed_apk_path: options[:signed_apk_path],
        keypass: options[:keypass]
    )

    zipalign(
      apk_path: "#{lane_context[SharedValues::SIGNED_APK_PATH]}"
    )

    supply(
     track: 'alpha',
     apk: "#{lane_context[SharedValues::SIGNED_APK_PATH]}"
   )

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end
end
end
# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://github.com/fastlane/fastlane#metrics
